"""Audited outer-loop supervisor for bounded RLT improvement campaigns."""

from supervisor.canonical import ContractError
from supervisor.budget import (
    BudgetExceeded,
    BudgetRequest,
    BudgetSnapshot,
    BudgetTracker,
    BudgetUsage,
)
from supervisor.contracts import (
    ApprovalEnvelope,
    ArtifactRef,
    BudgetEnvelope,
    CampaignSpec,
    CampaignState,
    Decision,
    DecisionRecord,
    EditMode,
    ParameterKind,
    ParameterRule,
    TrialEvidence,
    TrialState,
    TrialStatus,
)
from supervisor.ledger import EntityType, EventLedger, LedgerCorruption, LedgerEvent
from supervisor.enforcement import (
    EnforcementPolicy,
    MaterializedConfig,
    PatchFile,
    PolicyError,
    PolicyViolation,
    ProposalEnforcer,
    ValidationReport,
    materialize_config,
    parse_unified_diff,
    validate_python_source,
)
from supervisor.git_manager import (
    CheckResult,
    GitExperimentManager,
    GitOperationError,
    HarnessCheck,
    HypothesisSnapshot,
    PreparationRecord,
    PreparationStatus,
    append_preparation_to_ledger,
)
from supervisor.attempts import ProposalAttemptController, ProposalSessionResult
from supervisor.context import (
    ContextBundle,
    ContextRejected,
    PriorTrialSummary,
    SourceExcerpt,
    build_context,
)
from supervisor.proposals import (
    PROPOSAL_SCHEMA_HASH,
    AttemptAudit,
    AttemptStatus,
    AttemptType,
    Proposal,
    proposal_json_schema,
)
from supervisor.providers import (
    ClaudeCliProvider,
    FakeProposalProvider,
    ProposalProvider,
    ProviderCallResult,
    ProviderError,
    ProviderTimeout,
)
from supervisor.state import (
    CAMPAIGN_STATE_MACHINE,
    TRIAL_STATE_MACHINE,
    TransitionError,
)
from supervisor.coordinator import (
    CoordinatorError,
    IterationStatus,
    LedgerAnchor,
    OfflineCampaignCoordinator,
    OfflineIterationResult,
)
from supervisor.evaluation import (
    ArmIncumbentStore,
    EvaluationError,
    EvaluationResult,
    OfflineD1Evaluator,
)
from supervisor.objective_adapter import (
    ActorObjectiveAdapter,
    ObjectiveError,
    frozen_reference_objective,
)
from supervisor.reporting import (
    SYNTHETIC_NOTICE,
    ReportArtifact,
    ReportBundle,
    build_report_payload,
    write_report_bundle,
)
from supervisor.workers import (
    ExperimentWorker,
    FakeExperimentWorker,
    RunContract,
    WorkerError,
    WorkerScenario,
    WorkerSnapshot,
    WorkerState,
)

__all__ = [
    "ApprovalEnvelope",
    "ActorObjectiveAdapter",
    "ArmIncumbentStore",
    "ArtifactRef",
    "AttemptAudit",
    "AttemptStatus",
    "AttemptType",
    "BudgetExceeded",
    "BudgetEnvelope",
    "BudgetRequest",
    "BudgetSnapshot",
    "BudgetTracker",
    "BudgetUsage",
    "CAMPAIGN_STATE_MACHINE",
    "CampaignSpec",
    "CampaignState",
    "CheckResult",
    "ClaudeCliProvider",
    "ContractError",
    "CoordinatorError",
    "ContextBundle",
    "ContextRejected",
    "Decision",
    "DecisionRecord",
    "EditMode",
    "EnforcementPolicy",
    "EntityType",
    "EvaluationError",
    "EvaluationResult",
    "EventLedger",
    "FakeProposalProvider",
    "FakeExperimentWorker",
    "GitExperimentManager",
    "GitOperationError",
    "HarnessCheck",
    "HypothesisSnapshot",
    "IterationStatus",
    "LedgerCorruption",
    "LedgerEvent",
    "LedgerAnchor",
    "MaterializedConfig",
    "ObjectiveError",
    "OfflineCampaignCoordinator",
    "OfflineD1Evaluator",
    "OfflineIterationResult",
    "ParameterKind",
    "ParameterRule",
    "PatchFile",
    "PolicyError",
    "PolicyViolation",
    "PriorTrialSummary",
    "PROPOSAL_SCHEMA_HASH",
    "Proposal",
    "ProposalAttemptController",
    "ProposalEnforcer",
    "ProposalProvider",
    "ProposalSessionResult",
    "ProviderCallResult",
    "ProviderError",
    "ProviderTimeout",
    "ReportArtifact",
    "ReportBundle",
    "RunContract",
    "SYNTHETIC_NOTICE",
    "PreparationRecord",
    "PreparationStatus",
    "SourceExcerpt",
    "TrialEvidence",
    "TrialState",
    "TrialStatus",
    "TRIAL_STATE_MACHINE",
    "TransitionError",
    "ValidationReport",
    "WorkerError",
    "WorkerScenario",
    "WorkerSnapshot",
    "WorkerState",
    "ExperimentWorker",
    "append_preparation_to_ledger",
    "build_context",
    "build_report_payload",
    "frozen_reference_objective",
    "materialize_config",
    "parse_unified_diff",
    "proposal_json_schema",
    "validate_python_source",
    "write_report_bundle",
]
